# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "Test-Fulfilrequest-Rocketfy"
client_id = "2d6dabd7b0c7c824997a56299a08b8a2"
application_url = "https://6fb9-201-233-140-72.ngrok-free.app"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
use_legacy_install_flow = true

[auth]
redirect_urls = [
  "https://6fb9-201-233-140-72.ngrok-free.app/auth/callback",
  "https://6fb9-201-233-140-72.ngrok-free.app/auth/shopify/callback",
  "https://6fb9-201-233-140-72.ngrok-free.app/api/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "test-fulfilrequest-store.myshopify.com"
